### ISSUE TITLE
Automatic sparsity pattern aspect ration

### ISSUE THREAD

**Issue by Evizero** [Evizero/UnicodePlots.jl#22]
When using `spy` the size of the plot currently defaults do a 1:1 aspect ratio, which isn't generally the best choice. I should change the size to depend on the matrix size (within some reasonable bounds) to reflect the structure of the matrix

**Comment by Evizero** [comment]
I implemented a heuristic that makes the spy plot resemble the matrix structure more closely (within reason) and pushed it to master

1. if the plot, in which each element of the matrix resembles one pixel, fits in the size of the interactive terminal then it will be plotted that way

2. if you don't specify neither `height` nor `width` then the plot will try to resemble the aspect ratio of the matrix while trying to fit in the bounding box defined by the parameters `maxwidth` and `maxheight`

3. if you specify either `width` or `height` then the other one will be computed based on the aspect ratio and cropped by `maxwidth` and `maxheight`

4. if you specify both `width` and `height` then it will just use those specifications blindly

would be nice to get some feedback on this from people who use `spy`

cc: @dpo @jakebolewski

**Comment by Evizero** [comment]
This is also the last addition for 0.3 before I move completely over to 0.4

**Comment by jakebolewski** [comment]
I'll try this out hopefully today and report back.

**Comment by Evizero** [comment]
That would be nice, thanks! If things work out I'll tag a new version and finally move on to 0.4

**Comment by dpo** [comment]
I gave it a try. Many thanks for the improvements! I really like the different colors for positive and negative values. Is there such a thing as a colorbar in your package? Often, spy plots color elements based on their magnitude (i.e., in absolute value or modulus), rather than sign. It can be helpful to compute rough approximations to the matrix.

I find the default plot size a bit too big though. I typically don't work in a very large terminal, and I split it into several tmux panes. Changing `height` works, but I wonder if the defaults should be smaller (say, `height`  = 20 or so). Otherwise, they look fantastic and keeping the aspect ratio is great (I often work with rectangular matrices).

**Comment by Evizero** [comment]
you mean `maxheight` I presume? Makes sense, I'll reduce it a bit

**Comment by Evizero** [comment]
First of all thanks for the feedback and your time.

Concerning colorbar: I am afraid I simply don't have enough colors available in a standard terminal. There are terminals that support things like 256 colors but I haven't looked into that (yet).

Concerning plot size: I changed it so that if the session is interactive then it will automatically try to squeeze the plot into the terminal window unless `maxheight` or `maxwidth` are explicitly overwritten. Now it shouldn't matter what size terminal you work in (hopefully). Could you maybe check if this issue is resolved for you now?

**Comment by jakebolewski** [comment]
I love the changes to do the autoscaling based off the aspect ratio of the matrix.  I was trying to do this in my own code, but it was a hack.  Looks great, looking forward to the removal of deprecation warnings :-).

**Comment by Evizero** [comment]
Great! I am gonna go ahead and tag the changes now. I'll tackle the migration warnings after the upgrade to 0.4
