### ISSUE TITLE
Support for DejaVu Sans?

### ISSUE THREAD

**Issue by moehle** [Evizero/UnicodePlots.jl#37]
Hi,

First of all, thanks for the great package; I'm really enjoying it.

I'm having some trouble getting correct behavior with the popular font DevaVu Sans Mono (under LXTerminal, XTerm, and Gnome terminal).  It does work correctly, under,  eg, Droid Sans Mono, as well as several other fonts.  The problem is that the background dots all appear white, instead of the (black) background color.  Any ideas?

I attached an image under LXTerminal
![unicodeplots](https://cloud.githubusercontent.com/assets/12259007/10871493/85d4c9c2-809d-11e5-9ca6-a27329a332dd.png)

**Comment by Evizero** [comment]
Hi! thanks for trying stuff out.

Sadly, I don't think I can influence how certain fonts / consoles render the [Braille](https://en.wikipedia.org/wiki/Braille) characters. Sadly they seem to be treated very differently from one font to font. That is probably because their actual purpose is not for plotting. This package just abuses them in this way.

The only suggestion I can give is to either use a different font or a different canvas by specifying `canvas = BlockCanvas` (or `DotCanvas` or `AsciiCanvas`)
