### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by dpo** [Evizero/UnicodePlots.jl#4]
Thanks for a great plotting package. Thousands of times faster than anything else out there for Julia!

Here are a few feature requests:
1. add stair plots one by one (`stairs!()`)
2. a `spy()` function to plot sparsity patterns
3. add axis labels in addition to "ticks"
4. add `:bc` (bottom center) location (and perhaps `:tc` (top center))
5. colored annotations (e.g., for colored legends)

Here's the first feature:
```JULIA
function lineplot!{T <: Canvas, F <: Real, R <: Real}(plot :: Plot{T}, X :: Vector{F}, Y :: Vector{R}; color::     Symbol=:white, args...)
  X = convert(Vector{FloatingPoint},X)
  Y = convert(Vector{FloatingPoint},Y)
  drawLine!(plot, X, Y, color)
end

function stairs!{T <: Canvas, F <: Real, R <: Real}(plot :: Plot{T}, X :: Vector{F} , Y :: Vector{R}; args...)
  xVec = zeros(length(X) * 2- 1)
  yVec = zeros(length(X) * 2 - 1)
  xVec[1] = X[1]
  yVec[1] = Y[1]
  o = 0 
  for i = 2:(length(X))
    xVec[i + o] = X[i]
    xVec[i + o + 1] = X[i]
    yVec[i + o] = Y[i-1]
    yVec[i + o + 1] = Y[i]
    o += 1
  end 
  lineplot!(plot, xVec, yVec; args...)
end
```

And here's a primitive `spy()`:
```JULIA
function spy(A :: SparseMatrixCSC, args...)
  rows, cols, vals = findnz(A)
  nrow, ncol = size(A)
  canvas = BrailleCanvas(40, int(20 * nrow / ncol),
                         plotWidth=float(ncol)+1, plotHeight=float(nrow)+1)
  spyplot = Plot(canvas, args...)
  setPoint!(spyplot,
            convert(Vector{FloatingPoint}, cols),
            nrow + 1 - convert(Vector{FloatingPoint}, rows),
            :green)                                                                                                
  return spyplot
end
```

![screen shot 2015-08-18 at 10 20 41](https://cloud.githubusercontent.com/assets/38760/9332501/d6871bcc-4592-11e5-957b-6886226514a3.PNG)

**Comment by Evizero** [comment]
Hi! glad you like it.

- `:t` and `:b` for top and bottom center annotations are planned. 

- The axis labelling is also a good idea. Not sure yet how I'll make it play nice with the center left annotation though

- I was thinking about colored labels. I think I'll do it as follows. when you write `annotate!(plot, :l, n, ":red .. my line")` it will replace the :color substrings with a solid color unicode block. I think that will give a nice result. What do you think?

- I didn't think about multiple stairs yet! I will absolutely do that. not a lot of work. Colors will however probably be bad in mixed stairs that overlap

- ticks are hard. First I have to figure out a good way to compute a nice plot range, but I'm on it.

- by the way the issue you have with the top border being different from the rest of the border is already fixed in master but not yet tagged as I make little adjustments to the interface currently. 

- I have not worked with sparce matrices in julia yet, so I'll have to try that out a bit.

**Comment by dpo** [comment]
I'm not sure about color blocks in legends. I was thinking about colored text, but I guess there could also be a colored symbol (e.g., a small square) next to the legend text.

Here's an example with overlapping stairs:
![screen shot 2015-08-18 at 10 52 46](https://cloud.githubusercontent.com/assets/38760/9333364/8bdb58a4-4597-11e5-8829-2fbc3c565bbd.PNG)

It would be great if the plot color automatically changed as lines are added to the plot. I did that with
```JULIA
  colors = (:white, :blue, :red, :magenta, :yellow, :green, :cyan)
  ncolors = length(colors)

  for s = 1 : ns
    color = colors[(s-1) % ncolors + 1]
    stairs!(myplot, x, y, color=color)
  end 
```

**Comment by Evizero** [comment]
Mhm doesn't look too bad, however the left side for example is not really distinguishable. But I guess increasing height would help that. There is no real way around the color sharing issue anyway.

[ ] I like the automatic color change idea !

**Comment by dpo** [comment]
Great! Thanks.

**Comment by Evizero** [comment]
Thank you, I think the `spy` plot is a great addition. I already integrated it and it will be in the next version update soonish
![](https://github.com/Evizero/UnicodePlots.jl/raw/api_refactor/doc/img/spy.png)

**Comment by dpo** [comment]
Excellent. Many thanks!

**Comment by waldyrious** [comment]
Since this issue covers multiple feature requests, I thought I'd add this [neat summary](http://blog.leahhanson.us/using-asciiplotsjl.html) by @astrieanna of what ASCIIPlots.jl can do (since its README isn't that comprehensive). It might provide some additional ideas :) particularly the "Heat Map" section near the end, since I've seen this is already planned for UnicodePlots according to the README. The Conclusion section contains a bunch of other ideas, some of which could make sense here.

**Comment by Evizero** [comment]
Thanks! I have read this before and did take a look at ASCIIPlots.jl quite early (which gave me the idea to do a density canvas with these puppies: ░▒▓█). 

Heatmap - in my eyes - would be pretty much the look to density but just have positive and negative direction. What I am unsure of is if color alone is sufficient to distinguish if its positive or negative, or if I should do different symbols so that the plot makes sense even without color. Could use an opinion in that regard

**Comment by waldyrious** [comment]
MHO is that color should be an additional factor, but not one we ought to depend on. One possibility would be to use different patterns. Ideally that would be done using symbols with the same shape and only differing in the pattern, such as ▤▥▦ and ▧▨▩, but unfortunately those don't seem to come in separate visual weights. (That said, they may still be useful for something else, so I thought it could be worth mentioning them.)

So with that out of the question, maybe we could use separate symbols for positive and negative values, but rather than relying on ASCII characters like ASCIIPlots.jl does, one option would be to use for instance [these](http://www.fileformat.info/info/unicode/block/geometric_shapes_extended/images.htm). Unfortunately that block is rather recent (7.0) and is [only supported by the Symbola font](http://www.fileformat.info/info/unicode/block/geometric_shapes_extended/fontsupport.htm). Which means it's also not a viable solution in the near term :(

Yet another option would be to use an [arrow](http://unicode-table.com/en/sets/arrows-symbols/) progression, e.g. ⇡↑⇑⤊⟰ for positive values, and ⇣↓⇓⤋⟱ for negative ones (and empty space for zeros), but as you can probably see here, fonts may not implement a consistent sizes that would allow them to be used as a coherent set. I don't have any more ideas, but maybe these can at least provide some inspiration.

Btw I'm not exactly sure I got why this thread was closed. Do you prefer to continue the discussion elsewhere?

**Comment by Evizero** [comment]
Yeah these are nice idea. I we will have to see what works well.

Yes let's move this to a separate issue. I want to avoid confusing threads that stretch multiple versions

**Comment by Evizero** [comment]
by the way I really appreciate the effort you put into this!

**Comment by dpo** [comment]
Thanks for the recent additions!
