### ISSUE TITLE
createPlotWindow missing

### ISSUE THREAD

**Issue by tbreloff** [Evizero/UnicodePlots.jl#42]
I just realized that the UnicodePlots backend is broken in Plots.jl.  It can't find `UnicodePlots.createPlotWindow`... what's the new method I should use for this?

**Comment by Evizero** [comment]
Hi, sorry for that. Since its an internal function I didn't think twice about breaking changes. Yes, I am in an ongoing endeavour to clean up the code and to make the codebase comply with the Julia conventions (i.e. get rid of camelCaseStuff). `createPlotWindow` is now absorbed into an outer constructor of `Plot`. See [plot.jl](https://github.com/Evizero/UnicodePlots.jl/blob/master/src/plot.jl) starting from line 42. It has a slightly different signature now.
